package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements Serializable {


     private Integer codigoAlumno;
     private PadreDeFamilia padreDeFamilia;
     private Ubicaciondocumentos ubicaciondocumentos;
     private Domicilio domicilio;
     private String apePat;
     private String apeMat;
     private String primerNom;
     private String segundoNom;
     private String nacionalidad;
     private Date fechaNac;
     private String tipoDoc;
     private String numDoc;
     private String sexo;
     private String telfFijo;
     private String telfEmerg;
     private int tieneDeudas;
     private int estadoActivo;
     private String motivoRetiro;
     private Set matriculas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(PadreDeFamilia padreDeFamilia, Ubicaciondocumentos ubicaciondocumentos, Domicilio domicilio, String apePat, String apeMat, String primerNom, String segundoNom, String nacionalidad, Date fechaNac, String tipoDoc, String numDoc, String sexo, String telfFijo, String telfEmerg, int tieneDeudas, int estadoActivo, String motivoRetiro) {
        this.padreDeFamilia = padreDeFamilia;
        this.ubicaciondocumentos = ubicaciondocumentos;
        this.domicilio = domicilio;
        this.apePat = apePat;
        this.apeMat = apeMat;
        this.primerNom = primerNom;
        this.segundoNom = segundoNom;
        this.nacionalidad = nacionalidad;
        this.fechaNac = fechaNac;
        this.tipoDoc = tipoDoc;
        this.numDoc = numDoc;
        this.sexo = sexo;
        this.telfFijo = telfFijo;
        this.telfEmerg = telfEmerg;
        this.tieneDeudas = tieneDeudas;
        this.estadoActivo = estadoActivo;
        this.motivoRetiro = motivoRetiro;
    }
    public Alumno(PadreDeFamilia padreDeFamilia, Ubicaciondocumentos ubicaciondocumentos, Domicilio domicilio, String apePat, String apeMat, String primerNom, String segundoNom, String nacionalidad, Date fechaNac, String tipoDoc, String numDoc, String sexo, String telfFijo, String telfEmerg, int tieneDeudas, int estadoActivo, String motivoRetiro, Set matriculas) {
       this.padreDeFamilia = padreDeFamilia;
       this.ubicaciondocumentos = ubicaciondocumentos;
       this.domicilio = domicilio;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.primerNom = primerNom;
       this.segundoNom = segundoNom;
       this.nacionalidad = nacionalidad;
       this.fechaNac = fechaNac;
       this.tipoDoc = tipoDoc;
       this.numDoc = numDoc;
       this.sexo = sexo;
       this.telfFijo = telfFijo;
       this.telfEmerg = telfEmerg;
       this.tieneDeudas = tieneDeudas;
       this.estadoActivo = estadoActivo;
       this.motivoRetiro = motivoRetiro;
       this.matriculas = matriculas;
    }
   
    public Integer getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(Integer codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }
    public PadreDeFamilia getPadreDeFamilia() {
        return this.padreDeFamilia;
    }
    
    public void setPadreDeFamilia(PadreDeFamilia padreDeFamilia) {
        this.padreDeFamilia = padreDeFamilia;
    }
    public Ubicaciondocumentos getUbicaciondocumentos() {
        return this.ubicaciondocumentos;
    }
    
    public void setUbicaciondocumentos(Ubicaciondocumentos ubicaciondocumentos) {
        this.ubicaciondocumentos = ubicaciondocumentos;
    }
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public String getPrimerNom() {
        return this.primerNom;
    }
    
    public void setPrimerNom(String primerNom) {
        this.primerNom = primerNom;
    }
    public String getSegundoNom() {
        return this.segundoNom;
    }
    
    public void setSegundoNom(String segundoNom) {
        this.segundoNom = segundoNom;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public String getNumDoc() {
        return this.numDoc;
    }
    
    public void setNumDoc(String numDoc) {
        this.numDoc = numDoc;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelfFijo() {
        return this.telfFijo;
    }
    
    public void setTelfFijo(String telfFijo) {
        this.telfFijo = telfFijo;
    }
    public String getTelfEmerg() {
        return this.telfEmerg;
    }
    
    public void setTelfEmerg(String telfEmerg) {
        this.telfEmerg = telfEmerg;
    }
    public int getTieneDeudas() {
        return this.tieneDeudas;
    }
    
    public void setTieneDeudas(int tieneDeudas) {
        this.tieneDeudas = tieneDeudas;
    }
    public int getEstadoActivo() {
        return this.estadoActivo;
    }
    
    public void setEstadoActivo(int estadoActivo) {
        this.estadoActivo = estadoActivo;
    }
    public String getMotivoRetiro() {
        return this.motivoRetiro;
    }
    
    public void setMotivoRetiro(String motivoRetiro) {
        this.motivoRetiro = motivoRetiro;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


