package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements Serializable {


     private Integer idCronograma;
     private Date fechaIni;
     private Date fechaVenc;
     private String mesPago;
     private String tipoCronograma;
     private Set detallepagos = new HashSet(0);

    public Cronograma() {
    }

	
    public Cronograma(Date fechaIni, Date fechaVenc, String mesPago, String tipoCronograma) {
        this.fechaIni = fechaIni;
        this.fechaVenc = fechaVenc;
        this.mesPago = mesPago;
        this.tipoCronograma = tipoCronograma;
    }
    public Cronograma(Date fechaIni, Date fechaVenc, String mesPago, String tipoCronograma, Set detallepagos) {
       this.fechaIni = fechaIni;
       this.fechaVenc = fechaVenc;
       this.mesPago = mesPago;
       this.tipoCronograma = tipoCronograma;
       this.detallepagos = detallepagos;
    }
   
    public Integer getIdCronograma() {
        return this.idCronograma;
    }
    
    public void setIdCronograma(Integer idCronograma) {
        this.idCronograma = idCronograma;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public Date getFechaVenc() {
        return this.fechaVenc;
    }
    
    public void setFechaVenc(Date fechaVenc) {
        this.fechaVenc = fechaVenc;
    }
    public String getMesPago() {
        return this.mesPago;
    }
    
    public void setMesPago(String mesPago) {
        this.mesPago = mesPago;
    }
    public String getTipoCronograma() {
        return this.tipoCronograma;
    }
    
    public void setTipoCronograma(String tipoCronograma) {
        this.tipoCronograma = tipoCronograma;
    }
    public Set getDetallepagos() {
        return this.detallepagos;
    }
    
    public void setDetallepagos(Set detallepagos) {
        this.detallepagos = detallepagos;
    }




}


