package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0

import java.io.Serializable;




/**
 * Detallepago generated by hbm2java
 */
public class Detallepago  implements Serializable {


     private Integer codigoPago;
     private Transaccion transaccion;
     private Matricula matricula;
     private Cronograma cronograma;
     private Estandarespago estandarespago;
     private String mesPago;
     private int tipoPago;
     private int estadoPago;
     private String usoPago;

    public Detallepago() {
    }

	
    public Detallepago(Matricula matricula, Cronograma cronograma, Estandarespago estandarespago, String mesPago, int tipoPago, int estadoPago, String usoPago) {
        this.matricula = matricula;
        this.cronograma = cronograma;
        this.estandarespago = estandarespago;
        this.mesPago = mesPago;
        this.tipoPago = tipoPago;
        this.estadoPago = estadoPago;
        this.usoPago = usoPago;
    }
    public Detallepago(Transaccion transaccion, Matricula matricula, Cronograma cronograma, Estandarespago estandarespago, String mesPago, int tipoPago, int estadoPago, String usoPago) {
       this.transaccion = transaccion;
       this.matricula = matricula;
       this.cronograma = cronograma;
       this.estandarespago = estandarespago;
       this.mesPago = mesPago;
       this.tipoPago = tipoPago;
       this.estadoPago = estadoPago;
       this.usoPago = usoPago;
    }
   
    public Integer getCodigoPago() {
        return this.codigoPago;
    }
    
    public void setCodigoPago(Integer codigoPago) {
        this.codigoPago = codigoPago;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public Estandarespago getEstandarespago() {
        return this.estandarespago;
    }
    
    public void setEstandarespago(Estandarespago estandarespago) {
        this.estandarespago = estandarespago;
    }
    public String getMesPago() {
        return this.mesPago;
    }
    
    public void setMesPago(String mesPago) {
        this.mesPago = mesPago;
    }
    public int getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(int tipoPago) {
        this.tipoPago = tipoPago;
    }
    public int getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(int estadoPago) {
        this.estadoPago = estadoPago;
    }
    public String getUsoPago() {
        return this.usoPago;
    }
    
    public void setUsoPago(String usoPago) {
        this.usoPago = usoPago;
    }




}


