package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements Serializable {


     private Integer codDomicilio;
     private String direccion;
     private String distrito;
     private String departamento;
     private String provincia;
     private Set alumnos = new HashSet(0);

    public Domicilio() {
    }

	
    public Domicilio(String direccion, String distrito, String departamento, String provincia) {
        this.direccion = direccion;
        this.distrito = distrito;
        this.departamento = departamento;
        this.provincia = provincia;
    }
    public Domicilio(String direccion, String distrito, String departamento, String provincia, Set alumnos) {
       this.direccion = direccion;
       this.distrito = distrito;
       this.departamento = departamento;
       this.provincia = provincia;
       this.alumnos = alumnos;
    }
   
    public Integer getCodDomicilio() {
        return this.codDomicilio;
    }
    
    public void setCodDomicilio(Integer codDomicilio) {
        this.codDomicilio = codDomicilio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


