package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Estandarespago generated by hbm2java
 */
public class Estandarespago  implements Serializable {


     private Integer codEstandares;
     private String conceptoPago;
     private int montoPago;
     private Integer tipoPago;
     private Set detallepagos = new HashSet(0);

    public Estandarespago() {
    }

	
    public Estandarespago(String conceptoPago, int montoPago) {
        this.conceptoPago = conceptoPago;
        this.montoPago = montoPago;
    }
    public Estandarespago(String conceptoPago, int montoPago, Integer tipoPago, Set detallepagos) {
       this.conceptoPago = conceptoPago;
       this.montoPago = montoPago;
       this.tipoPago = tipoPago;
       this.detallepagos = detallepagos;
    }
   
    public Integer getCodEstandares() {
        return this.codEstandares;
    }
    
    public void setCodEstandares(Integer codEstandares) {
        this.codEstandares = codEstandares;
    }
    public String getConceptoPago() {
        return this.conceptoPago;
    }
    
    public void setConceptoPago(String conceptoPago) {
        this.conceptoPago = conceptoPago;
    }
    public int getMontoPago() {
        return this.montoPago;
    }
    
    public void setMontoPago(int montoPago) {
        this.montoPago = montoPago;
    }
    public Integer getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(Integer tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Set getDetallepagos() {
        return this.detallepagos;
    }
    
    public void setDetallepagos(Set detallepagos) {
        this.detallepagos = detallepagos;
    }




}


