package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements Serializable {


     private Integer codMatricula;
     private Aula aula;
     private Alumno alumno;
     private int estadoMatricula;
     private String motivoCancelacion;
     private int anoMatricula;
     private int deudaFinAno;
     private Date fechaMatricula;
     private Set detallepagos = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(Aula aula, Alumno alumno, int estadoMatricula, String motivoCancelacion, int anoMatricula, int deudaFinAno, Date fechaMatricula) {
        this.aula = aula;
        this.alumno = alumno;
        this.estadoMatricula = estadoMatricula;
        this.motivoCancelacion = motivoCancelacion;
        this.anoMatricula = anoMatricula;
        this.deudaFinAno = deudaFinAno;
        this.fechaMatricula = fechaMatricula;
    }
    public Matricula(Aula aula, Alumno alumno, int estadoMatricula, String motivoCancelacion, int anoMatricula, int deudaFinAno, Date fechaMatricula, Set detallepagos) {
       this.aula = aula;
       this.alumno = alumno;
       this.estadoMatricula = estadoMatricula;
       this.motivoCancelacion = motivoCancelacion;
       this.anoMatricula = anoMatricula;
       this.deudaFinAno = deudaFinAno;
       this.fechaMatricula = fechaMatricula;
       this.detallepagos = detallepagos;
    }
   
    public Integer getCodMatricula() {
        return this.codMatricula;
    }
    
    public void setCodMatricula(Integer codMatricula) {
        this.codMatricula = codMatricula;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public int getEstadoMatricula() {
        return this.estadoMatricula;
    }
    
    public void setEstadoMatricula(int estadoMatricula) {
        this.estadoMatricula = estadoMatricula;
    }
    public String getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(String motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }
    public int getAnoMatricula() {
        return this.anoMatricula;
    }
    
    public void setAnoMatricula(int anoMatricula) {
        this.anoMatricula = anoMatricula;
    }
    public int getDeudaFinAno() {
        return this.deudaFinAno;
    }
    
    public void setDeudaFinAno(int deudaFinAno) {
        this.deudaFinAno = deudaFinAno;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public Set getDetallepagos() {
        return this.detallepagos;
    }
    
    public void setDetallepagos(Set detallepagos) {
        this.detallepagos = detallepagos;
    }




}


