package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PadreDeFamilia generated by hbm2java
 */
public class PadreDeFamilia  implements Serializable {


     private String usuarioIdUsuario;
     private Usuario usuario;
     private String nombre1;
     private String nombre2;
     private String apePat;
     private String apeMat;
     private String numDoc;
     private int telefono;
     private String sexo;
     private int estadoActivo;
     private Set alumnos = new HashSet(0);

    public PadreDeFamilia() {
    }

	
    public PadreDeFamilia(Usuario usuario, String nombre1, String nombre2, String apePat, String apeMat, String numDoc, int telefono, String sexo, int estadoActivo) {
        this.usuario = usuario;
        this.nombre1 = nombre1;
        this.nombre2 = nombre2;
        this.apePat = apePat;
        this.apeMat = apeMat;
        this.numDoc = numDoc;
        this.telefono = telefono;
        this.sexo = sexo;
        this.estadoActivo = estadoActivo;
    }
    public PadreDeFamilia(Usuario usuario, String nombre1, String nombre2, String apePat, String apeMat, String numDoc, int telefono, String sexo, int estadoActivo, Set alumnos) {
       this.usuario = usuario;
       this.nombre1 = nombre1;
       this.nombre2 = nombre2;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.numDoc = numDoc;
       this.telefono = telefono;
       this.sexo = sexo;
       this.estadoActivo = estadoActivo;
       this.alumnos = alumnos;
    }
   
    public String getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(String usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre1() {
        return this.nombre1;
    }
    
    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public String getNumDoc() {
        return this.numDoc;
    }
    
    public void setNumDoc(String numDoc) {
        this.numDoc = numDoc;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEstadoActivo() {
        return this.estadoActivo;
    }
    
    public void setEstadoActivo(int estadoActivo) {
        this.estadoActivo = estadoActivo;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


