package entidades;
// Generated 24/06/2015 11:04:55 AM by Hibernate Tools 3.6.0

import java.io.Serializable;




/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements Serializable {


     private String idUsuario;
     private String passUsuario;
     private String rol;
     private String email;
     private PadreDeFamilia padreDeFamilia;

    public Usuario() {
    }

	
    public Usuario(String idUsuario, String passUsuario, String rol, String email) {
        this.idUsuario = idUsuario;
        this.passUsuario = passUsuario;
        this.rol = rol;
        this.email = email;
    }
    public Usuario(String idUsuario, String passUsuario, String rol, String email, PadreDeFamilia padreDeFamilia) {
       this.idUsuario = idUsuario;
       this.passUsuario = passUsuario;
       this.rol = rol;
       this.email = email;
       this.padreDeFamilia = padreDeFamilia;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public PadreDeFamilia getPadreDeFamilia() {
        return this.padreDeFamilia;
    }
    
    public void setPadreDeFamilia(PadreDeFamilia padreDeFamilia) {
        this.padreDeFamilia = padreDeFamilia;
    }




}


